### PR TITLE
Extend VatCode resource

### PR DESCRIPTION
**Pull request by iranl**
Adds get(), send() and Mapper to VatCode.

Includes fixes to listAll() code to:

1. Properly process options passed to listAll in the following format:

```php
$options['vattype'] = 'sales';
$vatcodeApiConnector = new \PhpTwinfield\ApiConnectors\VatCodeApiConnector($connection);
$vatcodes = $vatcodeApiConnector->listAll('*', 0, 1, 100, $options);
```

2. Handle situations where only one result is returned from listAll() and Twinfield uses a different format when returning results

### CODE REVIEW

**Comment by willemstuursma** [comment]
Thanks, it could use some tests but it looks fine. 

That's a lot of pull requests you are contributing! Working on a Twinfield related project?

**Comment by iranl** [comment]
> Thanks, it could use some tests but it looks fine.
> 
> That's a lot of pull requests you are contributing! Working on a Twinfield related project?

Been using the Twinfield API in about 5 projects using my own horrendous code since 2014 based on the PHP Example by Twinfield. But in my own defence there wasn't a lot of documentation or libraries like this one then. 

The deprecation of session login and switch to OpenID Authentication seemed like a good moment to replace my own code with this library, but the library lacks some functionality I currently use (like listAll() for articles and invoices and invoice VAT lines), so thats why I'm creating all these PR's.

**Comment by willemstuursma** [comment]
Thanks @iranl, nice to hear that you are liking the library. Looking forward to merging all the changes.

**Comment by iranl** [comment]
Superseded by #142

**Pull request closed without merging**
