### PR TITLE
Added collectmandate element

### PR DESCRIPTION
**Pull request by cwdt**
Added collect mandate element to package, also fixed typo

### CODE REVIEW

**Comment by Daanvm** [comment]
Hi @cwdt, thanks for your PR. Unfortunately, I'm afraid you've branched off an older version of this repository.

I've been working towards a 2.0 release for the past two weeks. A lot of the files you've changed no longer exist or are moved. I've also dropped support for php5 and moved towards php7.

It would be awesome if you could fix this PR or create a new one that is in the new v2.0 style, so I can merge your PR.

**Comment by cwdt** [comment]
Hi @Daanvm it was actually intentionally since we're using this package in production and really needed this functionality. Is it possible to update this one in the v1 version?

**Comment by Daanvm** [comment]
I couldn't trigger the build after I fixed the merge conflicts in the GitHub webinterface. Let's see how the build is doing, but I'm afraid the build for php 5.3 to 5.5 won't work.

**Comment by cwdt** [comment]
Thanks for merging though!

**Comment by Daanvm** [comment]
I've fixed the build and created a v1.1.0 release 👍

**Comment by cwdt** [comment]
Thanks!

**Pull request merged**
