### PR TITLE
Allow dates from Browse data to be null

### PR DESCRIPTION
**Pull request by axlon**
Right now querying nullable dates from the browse API will cause an exception, in my case the matchdate on Supplier transactions (code 200)

The next line of code will cause an exception:
```php
(new BrowseColumn)->setField('fin.trs.line.matchdate')->setVisible(true),
```

Exception: `Invalid date, expected in yyyymmdd format, got "".`

With this PR no exception is thrown and a `BrowseDataCell` with value `null` is returned instead

I opted to not change the Util::parseDate and parseDateTime methods themselves, because they are used in other places as well.

### CODE REVIEW

**Comment by willemstuursma** [comment]
@axlon `parseDateTime` already support `null`, I think it is fine to add it to `parseDate` as well.

**Comment by axlon** [comment]
@willemstuursma changed it in parseDate 👍

**Comment by willemstuursma** [comment]
Thanks for checking the usages.

**Comment by axlon** [comment]
@willemstuursma No problem! Could you tag a new release for this?

**Pull request merged**
